# -*- coding: utf-8 -*-
"""hospital_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvpZ5mg0JD1U4-HwgonfIYxJsYCf3aJO

# Hospital Data Cleaning & Transformation
**Module 2 — Data Cleaning & Transformation**

This notebook loads the raw hospital data, cleans it, and saves the cleaned result as a CSV file.

**Place this notebook in the same folder as `hospital_raw_data.csv`** — the paths below use filenames only, so everything reads/writes right next to the notebook.

**Steps covered:**
1. Load & inspect raw data
2. Remove duplicate records
3. Standardize department names & text fields
4. Handle missing patient data
5. Standardize date formats
6. Normalize healthcare indicators (rate/percentage columns)
7. Validate
8. Save cleaned CSV

## 1. Load Data
"""

import pandas as pd
import numpy as np

RAW_PATH = "hospital_raw_data.csv"
OUT_PATH_CSV = "hospital_cleaned.csv"

df = pd.read_csv(RAW_PATH)
print(f"Loaded {df.shape[0]} rows, {df.shape[1]} columns")
df.head()

"""## 2. Initial Data Quality Assessment
Check for duplicates, missing values, and inconsistent categories before cleaning.
"""

missing = df.isnull().sum()
missing = missing[missing > 0]
print("Columns with missing values:")
print(missing)
print()
print("Total missing %:", round(df.isnull().sum().sum() / df.size * 100, 2), "%")
print("Exact duplicate rows:", df.duplicated().sum())
print("Duplicate Patient IDs:", df.duplicated(subset=['Patient ID']).sum())

"""## 3. Remove Duplicate Records
Drop exact duplicate rows, and drop duplicate `Patient ID` entries (a patient admission record should be unique).
"""

rows_before = len(df)

exact_dupes = df.duplicated().sum()
df = df.drop_duplicates()

id_dupes = df.duplicated(subset=["Patient ID"]).sum()
df = df.drop_duplicates(subset=["Patient ID"], keep="first")

print(f"Removed {exact_dupes} exact duplicate rows")
print(f"Removed {id_dupes} duplicate Patient ID rows")
print(f"Rows: {rows_before} -> {len(df)}")

"""## 4. Standardize Text Fields & Department Names
Trim whitespace, normalize casing, and reconcile `Department` against a single canonical `Department ID` per department (guards against any stray mismatches).
"""

text_cols = df.select_dtypes(include="object").columns.tolist()

# Trim whitespace and normalize empty-string variants to NaN
for col in text_cols:
    df[col] = df[col].astype(str).str.strip()
    df.loc[df[col].isin(["nan", "None", ""]), col] = np.nan

# Title-case categorical/location fields (skip fields with acronyms like
# Insurance Provider "ICICI Lombard" or Doctor "Dr. Name", which are
# already well-formatted and would be broken by title-casing)
for col in ["Department", "Transfer_From_Department", "Transfer_To_Department",
            "Hospital Type", "City", "State",
            "Diagnosis", "Treatment", "Medication", "Equipment"]:
    df[col] = df[col].str.title()

print("Unique departments after standardization:")
print(sorted(df["Department"].dropna().unique()))

# Reconcile Department -> Department ID using the most common mapping
dept_id_map = (
    df.dropna(subset=["Department", "Department ID"])
      .groupby("Department")["Department ID"]
      .agg(lambda s: s.mode().iloc[0])
      .to_dict()
)
df["Department ID"] = df["Department"].map(dept_id_map).fillna(df["Department ID"])
df[["Department", "Department ID"]].drop_duplicates().sort_values("Department ID")

"""## 5. Handle Missing Patient Data

- **`Insurance Provider`** missing → the patient is self-paying, so we fill with `"Self-Pay"` rather than dropping the record.
- **`Transfer_To_Department`** / **`Transfer_Date`** missing → these are only populated when `Transferred == "Yes"`. A missing value here is structurally expected (no transfer occurred), so we encode it explicitly as `"Not Transferred"` instead of leaving a blank.
- Any remaining missing **numeric** values are filled with the column median; any remaining missing **text** values are filled with `"Unknown"` as a safety net.
"""

missing_before = df.isnull().sum().sum()
missing_pct_before = round(missing_before / df.size * 100, 2)

df["Insurance Provider"] = df["Insurance Provider"].fillna("Self-Pay")
df["Transfer_To_Department"] = df["Transfer_To_Department"].fillna("Not Transferred")
df["Transfer_Date"] = df["Transfer_Date"].fillna("Not Transferred")

num_cols = df.select_dtypes(include=np.number).columns
for col in num_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].median())

df[text_cols] = df[text_cols].fillna("Unknown")

missing_after = df.isnull().sum().sum()
missing_pct_after = round(missing_after / df.size * 100, 2)
print(f"Missing values: {missing_before} ({missing_pct_before}%) -> {missing_after} ({missing_pct_after}%)")

"""## 6. Standardize Date Formats
The raw data mixes `M/D/YYYY` and `YYYY-MM-DD HH:MM:SS` formats. Convert all date fields to a single ISO-8601 `YYYY-MM-DD` format for consistent Tableau/Excel parsing.
"""

for col in ["Admission Date", "Discharge Date"]:
    df[col] = pd.to_datetime(df[col], format="mixed", errors="coerce").dt.strftime("%Y-%m-%d")

# Transfer_Date mixes real dates with the "Not Transferred" placeholder
mask = df["Transfer_Date"] != "Not Transferred"
df.loc[mask, "Transfer_Date"] = pd.to_datetime(
    df.loc[mask, "Transfer_Date"], format="mixed", errors="coerce"
).dt.strftime("%Y-%m-%d")

df[["Admission Date", "Discharge Date", "Transfer_Date"]].head()

"""## 7. Normalize Healthcare Indicators
`Admissions_Rate_%_Derived` and `Bed_Occupancy_Rate_%` were stored as raw fractions (range ~0.0–1.4), while `Staff_Utilization_%_Derived` was already a true 0–100 percentage. Rescale the fraction columns ×100 so all rate indicators share one consistent percentage scale — required for meaningful comparison and reporting.
"""

print("Before normalization:")
print(df[["Admissions_Rate_%_Derived", "Bed_Occupancy_Rate_%", "Staff_Utilization_%_Derived"]].describe())

for col in ["Admissions_Rate_%_Derived", "Bed_Occupancy_Rate_%"]:
    df[col] = (df[col] * 100).round(2)
df["Staff_Utilization_%_Derived"] = df["Staff_Utilization_%_Derived"].round(2)

# Standardize Yes/No flag columns to consistent capitalization
for col in ["Bed Occupied", "Readmission", "Transferred"]:
    df[col] = df[col].str.capitalize()

print("\nAfter normalization:")
print(df[["Admissions_Rate_%_Derived", "Bed_Occupancy_Rate_%", "Staff_Utilization_%_Derived"]].describe())

"""## 8. Final Validation"""

final_missing_pct = round(df.isnull().sum().sum() / df.size * 100, 2)
print(f"Final missing-value rate: {final_missing_pct}%  (target: < 2%)")
assert final_missing_pct < 2.0, "Missing value threshold not met!"

print(f"Final shape: {df.shape}")
print(f"Duplicate rows remaining: {df.duplicated().sum()}")
print(f"Duplicate Patient IDs remaining: {df.duplicated(subset=['Patient ID']).sum()}")

"""## 9. Save Cleaned CSV
Save the cleaned `df` to `hospital_cleaned.csv`.
"""

df.to_csv(OUT_PATH_CSV, index=False)
print(f"Saved cleaned dataset to {OUT_PATH_CSV}")
print(f"Final shape: {df.shape}")
df.head()